SorrTask1029_mle_predictions
kaizen-ai/kaizenflow pull request #1033
Opened 2024-06-10 16:20 UTC by tkpratardan

- Added MLE predictions
- Increased the training set to 40k samples from 20k samples
- Added functions to compute stats on input df (value counts of classes and prior probabilites)

2024-06-10 21:34 UTC, sonaalKant requested changes

2024-06-10 21:34 UTC, sonaalKant commented on research_amp/soccer_prediction/sota_baseline_glm.py
> +        ).fit(maxiter=10)
hyper param should be global.

2024-06-10 21:34 UTC, sonaalKant commented on research_amp/soccer_prediction/sota_baseline_glm.py
> +    plt.show()
Similar to above.

2024-06-10 21:34 UTC, sonaalKant commented on research_amp/soccer_prediction/sota_baseline_glm.py
> +    # Plot the residuals.
```
poisson_model.params.plot(kind='bar', figsize=(10, 6), title='Model Coefficients', xlabel='Features', ylabel='Coefficient Value', legend=False)
plt.show()
```

2024-06-10 21:34 UTC, sonaalKant commented on research_amp/soccer_prediction/sota_baseline_glm.py
> +    s3.Bucket(bucket_name).upload_file(local_model_path, s3_model_path)
This should definitely be another method, which takes any model and filepath and saves the model in s3.

2024-06-10 21:47 UTC, tkpratardan commented on research_amp/soccer_prediction/sota_baseline_glm.py
> epsilon isn't too big?. Lets try to use all the hyperparams in config and outside functions so that the code is to tweak.

because we use logs in estimation, lower values of eplison implies higher values of log than that in the usual range ( no. of goals lies between 1-10)

2024-06-12 21:09 UTC, gpsaggese commented
Agree with @sonaalKant points.

The root cause is that we are writing too much code without thinking about the architecture / writing maintainable code.
The good news is that it's an easy problem to fix and we can help.

Let's focus on cleaning and re-organizing the code.

2024-06-21 00:09 UTC, closed without merging

2024-06-21 00:09 UTC, tkpratardan commented
@sonaalKant @gpsaggese Closing this PR and the file #1036 is meant to cater to the changes mentioned here. PR #1049