KaizenTask1046_Resume_resampling_Binance_bidask_data
kaizen-ai/kaizenflow pull request #1047
Opened 2024-06-13 18:56 UTC by Jd8111997

Issue [Resume resampling Binance bid/ask data](https://github.com/kaizen-ai/kaizenflow/issues/1046).

2024-06-13 23:08 UTC, sonaalKant requested changes

2024-06-13 23:08 UTC, sonaalKant commented on helpers/hs3.py
> +    E.g.: ``` aws_access_key_id=*** aws_secret_access_key=***
Always do a self PR review. If linter has messed thing fix.

2024-06-13 23:10 UTC, sonaalKant approved these changes

2024-06-13 23:18 UTC, merged

2024-06-14 00:34 UTC, Jd8111997 commented on helpers/hs3.py
> +    E.g.: ``` aws_access_key_id=*** aws_secret_access_key=***
Will keep in mind.