KaizenTask1052_Unit_test_populate_exchange_currency_tables
kaizen-ai/kaizenflow pull request #1053
Opened 2024-06-19 14:24 UTC by heanhsok

Task #1052

- Mock CCXT.
- Verify that the exchange_currency and currency_pair tables are populated correctly.

2024-06-19 14:36 UTC, heanhsok commented
I didn't include the mock db connection part because it looks like the `populate_exchange_currency_tables` function doesn't make use of `DbConnectionManager` from `im_v2.common.db.db_utils`. Please let me know if I miss something. @sonaalKant

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +    ccxt_patch = umock.patch.object(imvccdbut, "ccxt", spec=ccxt)
put it before all the functions, for ref see `im_v2/ccxt/data/extract/test/test_download_exchange_data_to_db_periodically.py`

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        self.tear_down_test()
not really our coding style but following reference at `amp/im_v2/ccxt/data/extract/test/test_download_exchange_data_to_db_periodically.py`

no need to do anything here, just a note for other reviewers

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        # Drop `exchange_name` table in the database.
no need for this comment imo, line is self-explanatory

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        # Drop `currency_pair` table in the database.
same

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        #
what are these empty lines encircling a comment?
no need

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        # Verify that the exchange_currency table is populated correctly.
if you refer an object name - put it in backticks
but in general avoid it at all cost
https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.coding_style.how_to_guide.md#referring-to-an-object-in-code-comments

2024-06-19 16:10 UTC, DanilYachmenev commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        #
same

2024-06-19 18:02 UTC, sonaalKant requested changes
Awesome Job!!. Test case passed, just one small fix required.

2024-06-19 18:02 UTC, sonaalKant commented on im_v2/ccxt/db/test/test_ccxt_db_utils.py
> +        query = f"SELECT * FROM exchange_currency"
it should be `exchange_name`

2024-06-19 19:31 UTC, sonaalKant approved these changes

2024-06-19 20:25 UTC, heanhsok commented
what's the next step? should we merge this PR?

2024-06-20 17:24 UTC, merged

2024-06-22 18:57 UTC, gpsaggese reviewed
Well done.