KaizenTask1085_unittest_rps
kaizen-ai/kaizenflow pull request #1087
Opened 2024-07-18 22:08 UTC by tkpratardan

Unit test RPS metric and added to a lib

2024-07-19 21:29 UTC, sonaalKant requested changes

2024-07-19 21:29 UTC, sonaalKant commented on research_amp/soccer_prediction/test/test_utils.py
> +        }
Can we make this simpler : 

In this test we are predicting correct class with high probability. In the second test we are predicting wrong with high probability. In third test we are predicting draw with high probability. 

Test 1 RPS < Test 3 RPS < Test2 RPS. Right??

2024-07-19 21:29 UTC, sonaalKant commented on research_amp/soccer_prediction/test/test_utils.py
> +        expected_rps = f"{expected_rps_val: .2f}"
Just put 1 value.

2024-07-19 21:29 UTC, sonaalKant commented on research_amp/soccer_prediction/test/test_utils.py
> +    def test2(self) -> None:
Same as above.

2024-07-24 15:56 UTC, sonaalKant commented on research_amp/soccer_prediction/test/test_utils.py
> +        expected_rps = f"{expected_rps_val: .2f}"
I think you misunderstood my comment, what you did was correct I meant to put one single value in expected_rps instead of computation. You can put the computation in comment. 

```
 # expected_rps  =             (
 #              (0.7 - 1) ** 2
 #           + (0.9 - 1) ** 2
 ...

expected_rps = x 
```

2024-07-26 15:04 UTC, tkpratardan commented on research_amp/soccer_prediction/test/test_utils.py
> +        }
Win < draw < loss is the expected order.

2024-07-26 17:32 UTC, sonaalKant approved these changes

2024-07-26 17:32 UTC, merged