Kaizen task1076 unit test hpandas dassert is days #1076
kaizen-ai/kaizenflow pull request #1102
Opened 2024-07-25 20:20 UTC by mihir1906

Created this PR for Issue #1076

Changes Made:

Implemented unit tests for dassert_is_days 
 
Testing:
Ran code through pylint and pytest.
```
test/test_hpandas.py::Test_dassert_is_days::test1 (0.00 s) PASSED                                                                                                                             [ 11%]
test/test_hpandas.py::Test_dassert_is_days::test2 (0.00 s) PASSED                                                                                                                             [ 22%]
test/test_hpandas.py::Test_dassert_is_days::test3 (0.00 s) PASSED                                                                                                                             [ 33%]
test/test_hpandas.py::Test_dassert_is_days::test4 (0.00 s) PASSED                                                                                                                             [ 44%]
test/test_hpandas.py::Test_dassert_is_days::test5 (0.00 s) PASSED                                                                                                                             [ 55%]
test/test_hpandas.py::Test_dassert_is_days::test6 (0.00 s) PASSED                                                                                                                             [ 66%]
test/test_hpandas.py::Test_dassert_is_days::test7 (0.00 s) PASSED                                                                                                                             [ 77%]
test/test_hpandas.py::Test_dassert_is_days::test8 (0.00 s) PASSED                                                                                                                             [ 88%]
test/test_hpandas.py::Test_dassert_is_days::test9 (0.00 s) PASSED                                                                                                                             [100%]
```
@samarth9008 please do let me know incase of any further suggestions/changes.

2024-07-26 21:36 UTC, samarth9008 reviewed
Good first PR, few nits from my side.

2024-07-26 21:36 UTC, samarth9008 commented on dev_scripts/client_setup/requirements.txt
>  docker-compose >= 1.29.0
No need to push changes on this file as it depends on individual system.

2024-07-26 21:36 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +        Timedelta is an exact integer number of days.
-> Test that function do not raise an exception with exact integer number of days.


Make this style of comments everywhere.

2024-07-26 21:36 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +        hpandas.dassert_is_days(timedelta)  # Should pass without exception
Code and comment not on the same line.

Check and remove everywhere.

2024-07-26 21:36 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +        self.assert_equal(actual_exception, expected_exception, fuzzy_match=True)
Add `# Check.` above `self.assert_equal` everywhere.

2024-07-26 21:36 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +
No empty lines in the code.

2024-07-26 21:36 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +               """
This should not change. Revert it back.

2024-07-29 12:53 UTC, mihir1906 commented on dev_scripts/client_setup/requirements.txt
>  docker-compose >= 1.29.0
The file encountered a few issues that affected the setup of the environment for the first time:

- The version specification for pytest was written as pytest >= "6.0.0" with quotes, which caused an error. It should be corrected to pytest >= 6.0.0 (without quotes).
- The line # pyyaml == 5.3.1 was commented out, which prevented the pyyaml package from being installed during setup.


Please let me know if these changes should be pushed.

2024-07-29 12:54 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        Timedelta is an exact integer number of days.
Noted.

2024-07-29 12:57 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +               """
I didn’t make any changes to the function itself; the only issue was that the comment got misaligned by mistake. I’ve fixed it and put the comment back in its original position.

2024-07-29 12:59 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        hpandas.dassert_is_days(timedelta)  # Should pass without exception
Noted.

2024-07-30 11:01 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +
No need for empty lines.

2024-07-30 11:01 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        # Should pass without exception
Comments end with `.`

2024-07-30 11:01 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        Test that function raises an exception with exact integer number of days and with 0 as minimum number of days.
reflow comment to 80 columns + linter.

2024-07-31 00:20 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +
I have removed the empty lines now.

2024-07-31 00:20 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        # Should pass without exception
Noted.

2024-07-31 00:48 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        Test that function raises an exception with exact integer number of days and with 0 as minimum number of days.
The comment has been reflowed to 80 columns. The linter has been run, and there are no errors for this class.

2024-08-01 15:55 UTC, sonaalKant approved these changes
LGTM.

2024-08-03 12:28 UTC, gpsaggese reviewed
Minor changes and merge

2024-08-03 12:28 UTC, gpsaggese commented on helpers/test/test_hpandas.py
> +        string2     1.333692    1.708455 ```
let's revert this part since the formatting got screwed up

2024-08-03 12:28 UTC, gpsaggese commented on dev_scripts/client_setup/requirements.txt
> +pytest >= 6.0.0
let's revert this file. I'll fix those things in the next main repo integration

2024-08-05 18:27 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        string2     1.333692    1.708455 ```
I have reverted this comment back with the correct formatting.

2024-08-05 19:23 UTC, mihir1906 commented on dev_scripts/client_setup/requirements.txt
> +pytest >= 6.0.0
I have reverted this file as it was earlier.

2024-08-14 17:52 UTC, sonaalKant requested changes

2024-08-14 17:52 UTC, sonaalKant commented on dev_scripts/client_setup/requirements.txt
Lets restore this file to master. Then we can merge.

2024-08-14 18:33 UTC, mihir1906 commented on dev_scripts/client_setup/requirements.txt
I have restored this file to master. Please check.

2024-08-15 14:57 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> -
Any reason to remove this code?

2024-08-15 16:16 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> -
I sincerely apologize for the accidental deletion that occurred during the merge conflict resolution. I restored he deletion and will ensure it doesn’t happen again.

2024-08-15 16:42 UTC, samarth9008 reviewed
Minor nits

2024-08-15 16:42 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +            # Should raise AssertionError
Add `.` in the end.

2024-08-15 16:42 UTC, samarth9008 commented on helpers/test/test_hpandas.py
> +        minimum days > 1.
> -> greater than

2024-08-15 17:06 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        Test that function raises an exception with duration < minimum number
Done.

2024-08-15 17:07 UTC, mihir1906 commented on helpers/test/test_hpandas.py
> +        minimum days > 1.
Done.

2024-08-15 17:20 UTC, samarth9008 reviewed
lg

2024-08-15 17:20 UTC, merged