update
kaizen-ai/kaizenflow pull request #1104
Opened 2024-07-30 04:38 UTC by jayati1397

This PR is for the Issue [#1103](https://github.com/kaizen-ai/kaizenflow/issues/1103)

This is the first draft to see if the solution is correct.
We are testing broker with two twap orders being submitted by just one instance of broker.

@samarth9008 please check and let me if the solution seems correct

2024-07-30 12:42 UTC, samarth9008 commented
Lets follow the process of naming the PR correctly as we did in the previous in the PRs.

2024-07-30 13:03 UTC, samarth9008 reviewed
High level looks good. Lets improve minor things based on the reviews of the previous PRs.

One question from my side.

2024-07-30 13:03 UTC, samarth9008 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
Is it possible to run it in the same event loop?

2024-07-30 13:10 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
no, it throws an error

2024-07-30 14:13 UTC, samarth9008 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
Can you post the error?

2024-07-30 14:33 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
`FAILED oms/broker/ccxt/test/test_ccxt_broker.py::TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler::test_multiple_twap_orders_submission - RuntimeError: Event loop is closed`

2024-07-30 14:42 UTC, samarth9008 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
Is there a way around? Trying to understand if its even possible.

@Sameep2808 Can you also take a look?

2024-07-30 16:24 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
I see the error you are facing this as we do close the given event loop at end of `hasynci.run` try using gather todo so that might work.

https://github.com/kaizen-ai/kaizenflow/blob/fc397074208ed649fa093b5f504a32ed02659fd5/helpers/hasyncio.py#L146

2024-07-30 19:26 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
@Sameep2808 would you mind elaborating this?

2024-07-30 19:35 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
Actually I am keeping the loop open and now it works

2024-07-31 06:36 UTC, Sameep2808 requested changes
Few Changes

2024-07-31 06:36 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +
We don't leave blank lines in between code

2024-07-31 06:36 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            # Check.
Can we use the same asserts present in the above test cases so that order outputs are generated and we can verify the runs.

you could update the outcomes as follows

```
pytest --update_outcomes  oms/broker/ccxt/test/test_ccxt_broker.py::TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler::test_submit_twap_orders_multiple_submission
```

2024-07-31 07:54 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            # Check.
@Sameep2808 does this look good? Do you want me to share the output?

2024-07-31 08:02 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            # Check.
@Sameep2808 I tried to run the command and it works fine but github workflow action is failing
`FAILED oms/broker/ccxt/test/test_ccxt_broker.py::TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler::test_submit_twap_orders_multiple_submission - AssertionError: 
################################################################################
The golden outcome doesn't exist: saved the actual output in '/app/oms/broker/ccxt/test/outcomes/TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler.test_submit_twap_orders_multiple_submission/output/test_ccxt_fills.txt.tmp'
################################################################################`

2024-07-31 12:37 UTC, samarth9008 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            # Check.
You will also need to push the txt files.

2024-07-31 14:23 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
@Sameep2808 @samarth9008 I marked close_event_loop=False for the first submission and made both the submissions run in that same loop but that throws an error when I added check statements like the previous test cases

`FAILED oms/broker/ccxt/test/test_ccxt_broker.py::TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler::test_submit_twap_orders_multiple_submission - AssertionError:  ################################################################################ The golden outcome doesn't exist: saved the actual output in '/app/oms/broker/ccxt/test/outcomes/TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler.test_submit_twap_orders_multiple_submission/output/test_ccxt_fills.txt.tmp' ################################################################################`

So would you mind explaining what does gather todo mean? how can I use that to run two submissions in one event loop

2024-07-31 16:06 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
```
pytest --update_outcomes  oms/broker/ccxt/test/test_ccxt_broker.py::TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler::test_submit_twap_orders_multiple_submission
```

try using this line it will automatically create golden outputs

2024-07-31 16:08 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                broker, orders_2, "test_ccxt_fills"
you will have to rename the tag to "test_ccxt_fills_2" ignorer to have two different outputs

2024-07-31 16:08 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            self._test_ccxt_trades(broker, ccxt_fills, "test_ccxt_trades")
Same here

2024-07-31 16:12 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        with hasynci.solipsism_context() as event_loop:
I did but then the github action workflow fails then

2024-07-31 19:40 UTC, Sameep2808 requested changes
The logic looks good but the code is to complicated to read right now. Lets use a for loop to call `_submit_twap_orders` and check results as I see we are repeating the same code twice

2024-07-31 19:40 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +            broker._async_exchange._positions = starting_positions
I would update the starting positions as per the fills if possible for accurate outputs of the runs.

2024-07-31 22:31 UTC, Sameep2808 requested changes
Good Job. Few changes.

Just a note we don't leave blank lines in-between code so just remove where ever applicable

2024-07-31 22:31 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +
No blank lines in between code

2024-07-31 22:31 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                fill_amount = curr_num_shares * fill_percents[i - 1]
Why are `_positions` getting updated before submitting the twap order.

2024-07-31 22:31 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                initial_position_amt = initial_position_amt - fill_amount
Also can you explain why this formula?

2024-07-31 22:31 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        curr_num_shares = 12
For easier understanding of the test lets start with 0 shares and then buy 10 shares in first bar and 5 shares in second bar

2024-08-01 02:07 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                fill_amount = curr_num_shares * fill_percents[i - 1]
the starting position represents the initial quantity of shares held before any TWAP orders are submitted. This starting position determines the available shares that can be sold or traded during the submission.

2024-08-01 02:12 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                initial_position_amt = initial_position_amt - fill_amount
For each iteration, the starting position is updated based on the fill amounts. This is calculated using the fill_percents array, which specifies the percentage of the order that gets filled during each time interval.

2024-08-01 03:34 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                initial_position_amt = initial_position_amt - fill_amount
Nope that seems correct although the method you are iterating through the fills is wrong. 

The way I see is just going to iterate between 1 and 2 while the `fill_percentage` is for 10 waves. it will only take 1 fill percent for each submit_twap order rather than taking 2 as the number of trades given to broker is 2.

Actually lets have a call and I'll explain what is expected vs what is happening here

2024-08-01 03:36 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                fill_amount = curr_num_shares * fill_percents[i - 1]
I see if you look closely in `get_test_broker` the initial positions are already set in the function.
https://github.com/kaizen-ai/kaizenflow/blob/423470c58122af11b12a1b9c3ea889abcad52342/oms/broker/ccxt/test/mock_exchange_test_case.py#L274
You must rather update the positions after submit twap order in order to add the positions which just got filled.

2024-08-01 03:40 UTC, Sameep2808 requested changes
Few Nits

2024-08-01 03:40 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +
Blank line

2024-08-01 03:40 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                [
Can we create a variable outside loop for this and pass it. This way it will be easier to update positions as well.

```
positions = [
    { "info": {"positionAmt": initial_position_amt},
      "symbol": "ETH/USDT:USDT",}
]
# Updating position 
positions[0]["info"]["positionAmt"] = updated_position_amt
broker._async_exchange._positions = positions
```

2024-08-01 18:38 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                shares = curr_num_shares[i - 1] * sum(
I have run this loop for calculating shares which is required for the next `exp` variable calculation

2024-08-01 20:32 UTC, Sameep2808 approved these changes
1 Nit. LGTM

2024-08-01 20:32 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                shares = curr_num_shares[i - 1] * sum(
Lets keep it simple as its anyway a test output lets add the expected_share value in a list outside the loop and use them

2024-08-01 22:00 UTC, gpsaggese commented on oms/broker/ccxt/test/outcomes/TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler.test_submit_twap_orders_multiple_submission/tmp.final.actual.txt
> +[Order:
No need to add this. This is just tmp.

2024-08-01 22:00 UTC, gpsaggese commented on oms/broker/ccxt/test/outcomes/TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler.test_submit_twap_orders_multiple_submission/tmp.final.expected.txt
> +[Order:
No need to add this. This is just tmp.

2024-08-01 22:00 UTC, gpsaggese commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                    close_event_loop=(i == len(initial_timestamps)),
let's add a bool

```
# Keep the event loop open for all the iterations and close it at the last one, so that ...
close_event_loop = 
```

2024-08-01 22:00 UTC, gpsaggese commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                # Assert ccxt fills and trades.
Assert -> Check

2024-08-02 03:32 UTC, jayati1397 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                    close_event_loop=(i == len(initial_timestamps)),
I didn't understand your point, do you want me to add a similar comment as above

2024-08-02 15:29 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +                    close_event_loop=(i == len(initial_timestamps)),
Basically what GP means is use a variable to store the boolean value and use it for better representation and also add comment explaining what's happening.

```
# Keep the event loop open for all the iterations and close it at the last one, so that ...
close_event_loop = i == len(initial_timestamps)
receipt, orders = hasynci.run(
                    coroutine,
                    event_loop=event_loop,
                    close_event_loop=close_event_loop,
)
```

2024-08-02 15:34 UTC, Sameep2808 commented on oms/broker/ccxt/test/test_ccxt_broker.py
> +        shares_sum = sum(
Just add the expected share numbers in form of a list no need to compute

```
shares_sum = [39, 25]
```

2024-08-05 14:35 UTC, Sameep2808 approved these changes
1 Change. LGTM

2024-08-05 14:35 UTC, Sameep2808 commented on oms/broker/ccxt/test/outcomes/TestCcxtBroker_UsingFakeExchangeWithDynamicScheduler.test_submit_twap_orders_multiple_submission/output/actual_orders1.txt.tmp
> +[Order:
Delete this file as its not required

2024-08-12 15:55 UTC, merged