Sorr task918 add unit test for split universe
kaizen-ai/kaizenflow pull request #996
Opened 2024-05-21 17:34 UTC by smitpatel49

#918

2024-05-21 23:04 UTC, sonaalKant requested changes
I will also add a corner case where group is 4 and part is 2.

2024-05-21 23:04 UTC, sonaalKant commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = " ".join([str(element) for element in universe_subset])
Lets not do this, instead convert the output from the method to str and then compare directly.

2024-05-22 01:13 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = " ".join([str(element) for element in universe_subset])
Hi, I will add that corner case. The output from the method is of list type, I felt that this was efficient to convert it to string type. Can you suggest a more suitable approach? Thanks.

2024-05-26 15:40 UTC, gpsaggese reviewed
Going in the right direction, but you need to read our docs and our code base more carefully.

2024-05-26 15:40 UTC, gpsaggese commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        Test if roup_size is 6 and universe_part is 2.
-> group_size

2024-05-26 15:40 UTC, gpsaggese commented on im_v2/common/data/extract/test/test_extract_utils.py
> +            map(str, imvcdeexut._split_universe(self.universe, 0, 0))
Pls read our doc with attention (e.g., docs/coding/all.write_unit_tests.how_to_guide.md and more)

Let's rewrite as
```
# Prepare inputs.
group_size = 0
universe_part = 0
# Call function under test.
act = imvcdeexut._split_universe(self.universe, group_size, universe_part)
# Check the output.
actual_str = " ".join(map(str, ...)
```

2024-05-26 15:40 UTC, gpsaggese commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = " ".join(
Let's factor out all the common code in a function and then you pass the input and the expected_str.

2024-05-26 15:40 UTC, gpsaggese commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        with pytest.raises(RuntimeError):
docs/coding/all.write_unit_tests.how_to_guide.md:31:    + [Always explain `self.assertRaises`](#always-explain-selfassertraises

2024-05-27 20:48 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = " ".join(
I understand the changes requested and will make them as you mentioned. I will go through the documentation once again. Thanks for the review @gpsaggese.

2024-05-27 20:59 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        with pytest.raises(RuntimeError):
I will put up the proper explanation. However, I cannot find `self.assertRaises` in the documentation.

2024-05-31 04:09 UTC, smitpatel49 commented
I am sorry for another PR. I made a minor mistake, but the code is not changed. I would request you to review it @gpsaggese, @sonaalKant, @samarth9008.

2024-05-31 15:40 UTC, samarth9008 reviewed
Some nits.

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +class TestSplitUniverse(hunitest.TestCase):
Lets add class doc string

```
Test that `_split_universe()` works correctly.
```

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    ]
I would move this inside the `get_universe_part()` function since it is constant for all the test cases

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    universe_part = 0
Add these two as params to `get_universe_part()` so you can test them with different values

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    # Call function under test.
No comment above the function

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    # Call function under test.
Instead there should be a doc string for the function

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    def get_universe_part(self) -> List:
make sure to add doc string of the function accordingly

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    def get_universe_part(self) -> List:
Lets also rename `get_universe_part` -> `helper`

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        # Return the actual output.
No need of this as we can read it from the code. Comments are for why the code is doing this rather than what the code is doing.

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        Test if both group_size and universe_part are 0.
param name in comment should be surrounded by back ticks.

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = str(self.get_universe_part())
I would do something like

```
actual = self.get_universe_part()
actual = str(actual)
expected = r"""
        []
        """
```

make sure this pattern is reflected everywhere

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        (This returns the whole list in the 1st part)
No need for this kind of comment in testing. Remove everywhere if present

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    universe_part = 0
Make sure to change the other part of code accordingly

2024-05-31 15:40 UTC, samarth9008 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        Test to check for error.
-> Test if the error is raised if no such part exists.

2024-05-31 22:43 UTC, smitpatel49 commented
Thanks for the review @samarth9008, I have updated the code accordingly.

2024-06-03 12:24 UTC, samarth9008 commented
Pls resolve the conversation if the changes are made.

2024-06-03 13:20 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        """
In very rare cases we can refer to objects on docstrings, unit test methods are such cases sometimes
But it should be demonstrated rather like a list of param-value elements in order to ease processing for readers
since you already have class docstring, here i'd do simply
```
"""
group_size = 0
universe_part = 0
"""
```

2024-06-03 13:20 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +                    """
unnecessary indentations

should be 
```
expected_str = r"""
[]
"""
```
you've run linter, right?
weird it hasn't fixed it

2024-06-03 13:20 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        self.assert_equal(actual_str, expected_str, fuzzy_match=True)
same comments for all the other test methods

2024-06-03 13:20 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        """
here we have an assert so
```
"""
Check that the error is raised if universe does not have input part.

group_size = 6
universe_part = 6
"""
```

I'd even take `universe_part = 7` just for more clarity

2024-06-03 13:22 UTC, DanilYachmenev commented
pls read https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.submit_code_for_review.how_to_guide.md#save-reviewer-time, particularly part about managing PR labels
pls follow it

2024-06-03 13:25 UTC, gpsaggese commented on im_v2/common/data/extract/test/test_extract_utils.py
>              self.check_df_output(resampled_df2, None, None, None, exp_df2)
What happened to this deleted code? Is it a missing merge from master?

2024-06-03 21:18 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
>              self.check_df_output(resampled_df2, None, None, None, exp_df2)
I think it might be a merge missing from master, as I am sure I haven't changed any other part of the code.

2024-06-03 21:20 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +                    """
I did. I made the change later when I was confused from another review. I undid it again.

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
>              self.check_df_output(resampled_df2, None, None, None, exp_df2)
@smitpatel49 pls return this code back since it is still in master

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = str(actual)
merge it all in one line
no need for comments, self-explanatory lines
```
actual = str(cm.exception)
```

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        # Call function under test.
no need as well, self-explanatory moment

we aim to comment as much as possible, but in some cases, mostly in tests, such comments are not really needed since tests are all about calling a tested function and comparing its outcome with expected

what you need to comment are some pivotal code moments which are not self-evident from the action athat is being implemented

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        group_size = 0 universe_part = 0.
split on 2 lines
```
"""
group_size = 0
universe_part = 0
"""
```
or does linter fixes it?

if the poblem is i linter, lets move docstring line from the class docstring to the each test method (except for the one with error exception check) and remove it from the class
so it will be

```
"""
Check that universe is split correctly.

group_size = 0
universe_part = 0
"""
```

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        # Get the actual output from helper function.
no need for this comment, helper docstring explain it

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = str(actual)
you do this in every test method
so lets move it to helper function and change its docstring to
`Run the function and get a string representation of its output.`

2024-06-04 11:30 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        # Check the output.
overall no need for comments here
they repeat over and over without doing much really

although you can add clarity this way:
```
group_size = 6
universe_part = 1
actual = self.helper(group_size, universe_part)
expected = r"""
...
"""
self.assert_equal(actual, expected)
```

fix all the other test methods accordingly
read https://github.com/kaizen-ai/kaizenflow/blob/master/docs/coding/all.coding_style.how_to_guide.md#dont-hardwire-params-in-a-function-call

2024-06-05 02:39 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
>              self.check_df_output(resampled_df2, None, None, None, exp_df2)
I have added the code back. I am still uncertain of how it got deleted. Sorry for the inconvenience.

2024-06-05 14:43 UTC, DanilYachmenev reviewed
fix and ready to merge

2024-06-05 14:43 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        Run the function and get ta string representation of its output.
-> `... and get a string ...`
typo

2024-06-05 14:43 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        actual_str = str(actual)
this one is not done
move `actual_str = str(actual)` to `helper()` function and update each test method accordingly

2024-06-05 14:43 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        self.assert_equal(actual_str, expected_str, fuzzy_match=True)
do we need `fuzzy_match=True`?
try to run without it and if it is required lets keep it but if not - remove

2024-06-05 14:43 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        self.assert_equal(actual_str, expected_str, fuzzy_match=True)
this one is basically identical to `test6`, no need, remove

2024-06-05 14:43 UTC, DanilYachmenev commented on im_v2/common/data/extract/test/test_extract_utils.py
> +    def test6(self) -> None:
remember to name it `test5` after you implement the comment above

2024-06-06 09:23 UTC, smitpatel49 commented on im_v2/common/data/extract/test/test_extract_utils.py
> +        self.assert_equal(actual_str, expected_str, fuzzy_match=True)
I think it is required as I tried without it and the `expected_str` to be in one line.

2024-06-06 13:03 UTC, DanilYachmenev reviewed
lgtm

2024-06-06 22:08 UTC, samarth9008 reviewed
LG

2024-06-06 22:09 UTC, samarth9008 approved these changes

2024-06-06 22:29 UTC, merged